.TH SWAP "1" "November 2003" "" ""
.SH NAME
swap \- swap two files
.SH SYNOPSIS
\fBswap\fR [-q] file1 file2
.SH OPTIONS
\fB-q\fR	quiet
.SH NOTES
Swap works with any file/file, dir/dir, file/dir combination.
.br
If either file is a symbolic link, swap will not proceed.
.SH DISCLAIMER
This is a hack rather than a serious program.
.br
Swap has never lost files for me, but please use with caution.
.SH AUTHOR
Steven Atkinson (stevenaaus (at) yahoo (dot) com)
